version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: app_modernization
      RABBITMQ_DEFAULT_PASS: app_modernization

volumes:
  rabbitmq_data:
    driver: local
